// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "ai.providers": string;
      "ai.models": string;
      "ai.selection.chat": string;
      "ai.selection.agent": string;
      "ai.selection.vision": string;
      "ai.selection.translation": string;
      "ai.selection.embedding": string;
      "ai.temperature": number;
      "ai.toolConcurrency": number;
      "ai.maxIterations": number;
      "ai.multiStepPilot": boolean;
      "ai.model.maxContext": number;
      "search.queryRewrite": boolean;
      "search.rerankEnabled": boolean;
      "search.rerankModel": string;
      "search.qualityMemory": string;
      "search.qualityMemory.high": string;
      "search.web.defaultProvider": string;
      "search.web.addedSources": string;
      "search.web.serpapi.apiKey": string;
      "search.web.brave.apiKey": string;
      "search.web.tavily.apiKey": string;
      "search.web.google.apiKey": string;
      "search.web.google.cx": string;
      "search.web.serper.apiKey": string;
      "search.web.perplexity.apiKey": string;
      "search.web.exa.apiKey": string;
      "search.web.bing.apiKey": string;
      "search.web.searxng.instanceUrl": string;
      "apis.semanticScholar.apiKey": string;
      "apis.openalex.apiKey": string;
      "apis.core.apiKey": string;
      "apis.dimensions.apiKey": string;
      "apis.pubmed.apiKey": string;
      "apis.unpaywall.email": string;
      "apis.wiley.tdmToken": string;
      "apis.elsevier.apiKey": string;
      "apis.github.token": string;
      "apis.uspto.apiKey": string;
      "apis.epo.consumerKey": string;
      "apis.epo.consumerSecret": string;
      "apis.lens.token": string;
      "apis.pqai.token": string;
      "apis.jpo.apiKey": string;
      "apis.kipris.apiKey": string;
      "embedding.mode": string;
      "embedding.local.model": string;
      "pdfParser.backend": string;
      "pdfParser.backendFallback": boolean;
      "pdfParser.opendataloader.enabled": boolean;
      "pdfParser.opendataloader.tableEnable": string;
      "pdfParser.opendataloader.returnImages": boolean;
      "pdfParser.opendataloader.timeout": number;
      "pdfParser.opendataloader.autoWatch": boolean;
      "pdfParser.opendataloader.useStructTree": boolean;
      "pdfParser.mineru.mode": string;
      "pdfParser.mineru.apiToken": string;
      "pdfParser.mineru.serverUrl": string;
      "pdfParser.mineru.model": string;
      "pdfParser.mineru.language": string;
      "decision.mode": string;
      "decision.model": string;
      "decision.screen.include": number;
      "decision.screen.exclude": number;
      "decision.endpoint": string;
      "decision.apiKey": string;
      "translate.enabled": boolean;
      "translate.auto": boolean;
      "translate.maxChars": number;
      "translate.engineType": string;
      "translate.google.apiKey": string;
      "translate.bing.apiKey": string;
      "translate.bing.region": string;
      "translate.deepl.apiKey": string;
      "translate.deepl.useFree": boolean;
      "translate.custom.apiUrl": string;
      "translate.custom.apiKey": string;
      "translate.custom.model": string;
      "discovery.blacklist": string;
      "discovery.whitelist": string;
      "pdfIndexer.lastFullTextVersion": number;
    };
  }
}
