/**
 * Shared constants used across multiple modules.
 * Single source of truth to avoid duplicated definitions.
 */

/** Default soul ID for global (non-entity-specific) conversations */
export const GLOBAL_SOUL_ID = "__global__";

/** Zotero preference prefix for this add-on */
export const PREF_PREFIX = "extensions.zotero.leadero";

/**
 * Safe batch size for SQLite IN-clauses.
 * SQLite's SQLITE_MAX_VARIABLE_NUMBER defaults to 999;
 * 900 leaves room for other parameters in the same query.
 */
export const SAFE_BATCH_SIZE = 900;

/** SQLite's maximum number of host parameters per statement */
export const SQLITE_MAX_VARIABLES = 999;

/** Default AI weight for score fusion (0 = heuristic only, 1 = AI only) */
export const DEFAULT_AI_WEIGHT = 0.7;

/**
 * Zotero tag applied to notes generated by AI (X2 provenance).
 * Machine-detectable via item.getTags() — distinguishes AI-generated content
 * from human-written notes for transparency and compliance (e.g. journal AI
 * usage declarations). Shared across all AI note-creation paths.
 *
 * Lives here (shared layer) rather than in `modules/noteTemplate` so core
 * note-creation paths can read it without importing `src/modules/**` (C-7);
 * `modules/noteTemplate` re-exports it for its existing consumers.
 */
export const LEADERO_AI_TAG = "leadero-ai-generated";
